import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";

import "@/public/vendors/feather/feather.css";
import "@/public/vendors/ti-icons/css/themify-icons.css";
import "@/public/vendors/css/vendor.bundle.base.css";

import "@/public/vendors/datatables.net-bs4/dataTables.bootstrap4.css";
import "@/public/vendors/ti-icons/css/themify-icons.css";
import "@/public/js/select.dataTables.min.css";

import "@/public/css/vertical-layout-light/style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script src="/vendors/js/vendor.bundle.base.js" />

      <Script src="/vendors/chart.js/Chart.min.js" />
      <Script src="/vendors/datatables.net/jquery.dataTables.js" />
      <Script src="/vendors/datatables.net-bs4/dataTables.bootstrap4.js" />
      <Script src="/js/dataTables.select.min.js" />

      <Script src="/js/off-canvas.js" />
      <Script src="/js/hoverable-collapse.js" />
      <Script src="/js/template.js" />
      <Script src="/js/settings.js" />
      <Script src="/js/todolist.js" />

      <Script src="/js/dashboard.js" />
      <Script src="/js/Chart.roundedBarCharts.js" />
    </html>
  );
}
